Fix RPM build: translate '-' to '~' in version for pre-release tags
RPM's Version: field forbids hyphens (reserved as Version/Release separator).
Tags like v0.1.0-beta.1 were causing:
  error: line 2: Illegal char '-' (0x2d) in: Version: 0.1.0-beta.1

Replace '-' with '~' in the RPM version only (RPM/dpkg pre-release convention).
Debian control/changelog keep the original hyphenated version.